fix

diff --git a/inference_service/Dockerfile b/inference_service/Dockerfile
--- a/inference_service/Dockerfile
+++ b/inference_service/Dockerfile
@@ -14,7 +14,7 @@ RUN apt-get update && apt-get install -y \
     git \
     && rm -rf /var/lib/apt/lists/*
 
-# 让 python = python3（很重要）
+    # 让 python = python3（很重要）
 RUN ln -s /usr/bin/python3 /usr/bin/python
 
 # 升级 pip
@@ -22,31 +22,35 @@ RUN python -m pip install --upgrade pip
 
 # Copy requirements first (for better caching)
 # COPY wheels /app/wheels
-RUN python -m pip install torch torchvision torchaudio   --index-url https://download.pytorch.org/whl/cu121 -i https://pypi.tuna.tsinghua.edu.cn/simple
+RUN python -m pip install torch torchvision torchaudio   --index-url https://download.pytorch.org/whl/cu121
 # RUN pip install /app/wheels/*.whl
 # RUN rm -rf /app/wheels
-COPY ./.u2net /root/.u2net
+# COPY ./.u2net /root/.u2net
 COPY requirements.txt .
 COPY diffusers /app/diffusers
 
-RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
+RUN pip install -r requirements.txt
 RUN pip install /app/diffusers
 
 # Install Python dependencies
 
 # Pre-download rembg model (this will download to ~/.u2net/)
-RUN python -c "from rembg import new_session; new_session('./app/.u2net')" || echo "Warning: rembg model download failed"
+# RUN python -c "from rembg import new_session; new_session('')" || echo "Warning: rembg model download failed"
 
 # Copy application code
 
 # Create output directories
 RUN mkdir -p app/outputs/bg_removed app/outputs
-
+RUN pip install -U "huggingface_hub[hf_transfer]" -i https://pypi.tuna.tsinghua.edu.cn/simple
+ENV HF_HUB_ENABLE_HF_TRANSFER=1
+RUN hf download Gulraiz00/u2net --local-dir ~/.u2net
+RUN hf download black-forest-labs/FLUX.2-klein-4B --local-dir /app/flux2-klein
 COPY . /app
 
+CMD ["python", "handler.py"]
 # Expose ports
-EXPOSE 8000 8001
+# EXPOSE 8000 8001
 
-# Default command (can be overridden)
-CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
+# # Default command (can be overridden)
+# CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
 
